"""Phase 12: writes frontend/src/lib/examples.js, the "load example" menu of the interface.

    python frontend/scripts/make_examples.py          (from the project root, inside the venv)

The examples are the hand-made emails of the API self-test (src/router/selftest.py), so what the menu shows is what the tests check: the David email of
master document Section 6.7, an exact-domain spoof, a credential request, an honest internal email, a body pasted without headers, an account-takeover
thread and an email that carries script payloads in every part (the XSS test). All names, addresses and account numbers are made up. The output holds
only ASCII (every other character is a \\u escape), so the file cannot hide a character.
"""

import json
from pathlib import Path

from src.api.selftest import XSS_PAYLOADS
from src.router.selftest import (BODY_ONLY, DAVID_GMAIL, HIJACK_TEXT, HONEST, JOHN, PARAGRAPHS, PHISH_GMAIL, SPOOF, calm_thread, eml)

OUT = Path(__file__).resolve().parents[1] / "src" / "lib" / "examples.js"


def xss_email():
    """The David email with a script payload in the greeting, the Subject, the display name and the signature (the payloads of the self-test)."""
    payload = " ".join(p for p in XSS_PAYLOADS if "\n" not in p)
    mail = DAVID_GMAIL.replace("Hi Maria,", "Hi %s," % payload, 1)
    mail = mail.replace("Subject: Urgent wire", "Subject: %s" % XSS_PAYLOADS[0], 1)
    mail = mail.replace("From: David Chen <", 'From: "%s" <' % XSS_PAYLOADS[1].replace('"', "'"), 1)
    return mail.replace("Finance Director", "Finance Director %s" % XSS_PAYLOADS[2], 1)


def examples():
    takeover = calm_thread(4) + [eml(4, JOHN, "Re: Invoice 77", HIJACK_TEXT, previous=PARAGRAPHS[3], ip="52.10.20.30")]
    return [
        {"id": "david", "title": "Wire request from a free mailbox (the David email)", "kind": "email", "email": DAVID_GMAIL, "orgDomain": "",
         "note": "Claims to be Finance at the company, writes from gmail.com and asks for a wire with urgency and secrecy: every check contradicts it."},
        {"id": "spoof", "title": "The company's own domain, but authentication fails", "kind": "email", "email": SPOOF, "orgDomain": "",
         "note": "The From address is the company's, but its DMARC check failed: a forged sender."},
        {"id": "phish", "title": "IT help desk asks for a password from a free mailbox", "kind": "email", "email": PHISH_GMAIL, "orgDomain": "",
         "note": "A credential request that claims to be internal and comes from gmail.com."},
        {"id": "honest", "title": "An honest internal email", "kind": "email", "email": HONEST, "orgDomain": "",
         "note": "Low risk: the claims are checked and nothing contradicts them."},
        {"id": "body", "title": "A body pasted without headers", "kind": "email", "email": BODY_ONLY, "orgDomain": "",
         "note": "Only the text is known, so nothing about the sender can be checked: the score can only come from the tactics. Read the coverage note."},
        {"id": "takeover", "title": "Account takeover inside a thread (5 messages)", "kind": "thread", "messages": takeover, "orgDomain": "",
         "note": "Four calm messages, then the same sender asks for a new bank account with urgency. The thread verifier finds the flip point."},
        {"id": "xss", "title": "Script payloads in every part (XSS test)", "kind": "email", "email": xss_email(), "orgDomain": "",
         "note": "Everything below must appear as plain text. Nothing may run, and no alert box may open."},
    ]


def main():
    header = ("// GENERATED by frontend/scripts/make_examples.py from the hand-made emails of src/router/selftest.py. Do not edit by hand.\n"
              "// All names, addresses and account numbers are made up. Only ASCII characters appear here (the rest are escapes).\n\n")
    body = "export const EXAMPLES = " + json.dumps(examples(), indent=2, ensure_ascii=True) + "\n"
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(header + body, encoding="ascii")
    print("wrote %s (%d examples, %d bytes)" % (OUT, len(examples()), OUT.stat().st_size))


if __name__ == "__main__":
    main()
